### PR TITLE
Adding information of config transfer

### PR DESCRIPTION
**Pull request by cybersonic**
As with previous PRs I think since this is an actual transfer we need a from -> to info there.

### CODE REVIEW

**Comment by bdw429s** [comment]
@cybersonic Is there a reason to include the "to" in this one, but not in the first pull?  Also, FWIW, the `import`, `export`, and `transfer` commands all do the exact same thing and there are no restrictions on what the `to` and `from` can be.  Meaning
```
cfconfig import   from=foo to=bar
cfconfig export   from=foo to=bar
cfconfig transfer from=foo to=bar
```
all do the same exact thing.  There's only 3 commands for readability (and the args in different orders)

But point being, if it makes sense to output something on one command, it probably makes sense to output the same thing on all 3 commands.  I'm only a bit reticent about showing the full path in every case as it's more/less an implementation detail.  e.g. if someone types
```
cfconfig transfer from=foo.json to=myCommandBoxServer
```
Do they really care what the long, boring path is behind the scenes for that CommandBox server?  Will it just be confusing to always show it to them?  Questions for the ages.

**Comment by cybersonic** [comment]
I get you, I was stimped with the transfer one too hence the `to` & `from` being added. 

In the import, I want to know where I am getting the data from (some file of my choosing usually), export; where I am exporting the data to, usually a file of my own choosing too. The transfer is a bit more of a tricky one hence I did from / to . 

That is my thinking anyway ... just trying to cover the main usecases

**Comment by cybersonic** [comment]
As a side note, I am having to do these pulls from the github interface so apologies for the disparate PRs

**Comment by bdw429s** [comment]
> I am getting the data from (some file of my choosing usually).

Right, and I guess that's the assumption I wasn't sure if it was safe to make.  Sure, in your case, you only care about one of the args, but the commands are generic enough, another user using the params differently may have the opposite desire.  

That said, it's probably not worth getting hung up on-- I'm ok catering to what seems to be the most common scenarios.  Either way, it's an improvement.  We can adjust if the output is too messy in some cases.

> apologies for the disparate PRs

Not a problem at all

**Pull request merged**
